name: CoinEx Trading Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: pip install -r requirements.txt

      # Step 4: Linting (Optional)
      - name: Lint Code
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      # Step 5: Run Tests
      - name: Run Tests
        run: pytest

      # Step 6: Verify Secrets (Optional)
      - name: Check API Key and Secret
        run: |
          if [[ -z "$ACCESS_ID" || -z "$SECRET_KEY" ]]; then
            echo "ACCESS_ID or SECRET_KEY environment variables are not set!"
            exit 1
          fi

      # Step 7: Run Trading Script
      - name: Execute Trading Script
        env:
          ACCESS_ID: ${{ secrets.ACCESS_ID }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          python coinex.py
